'use client';
import {Button} from '@/components/ui/button';
import type {DescentReadout} from '@/lib/descent';
type Props={data:DescentReadout;playing:boolean;auto:boolean;onAuto:()=>void;onPlay:()=>void;onRestart:()=>void;onExit:()=>void;onControl:(key:string,down:boolean)=>void};
export default function DescentHUD({data,playing,auto,onAuto,onPlay,onRestart,onExit,onControl}:Props){
 const steeper=data.ahead>Math.max(data.slope,0)+4;
 const angle=(value:number)=>`~${Math.round(Math.abs(value))}°`;
 return <div className="descent-ui">
 <div className="descent-top"><div><span className="eyebrow">ROTWENG 11 / STANDARD 7</span><h2>{data.finished?'Descent complete':playing?'Find your line.':'Ready when you are.'}</h2></div><Button variant="secondary" onClick={onExit}>Exit POV</Button></div>
 <div className="descent-instruments"><div className="slope-instrument"><span>SLOPE HERE</span><div className="slope-value"><strong>{angle(data.slope)}</strong><svg width="72" height="44" viewBox="0 0 72 44" aria-label="Incline diagram"><path d="M4 38H68" stroke="#ffffff40" fill="none"/><path d={data.slope>=0?`M8 ${38-Math.tan(Math.min(Math.abs(data.slope),40)*Math.PI/180)*50}L58 38`:`M8 38L58 ${38-Math.tan(Math.min(Math.abs(data.slope),40)*Math.PI/180)*50}`} stroke="#d8eef4" strokeWidth="3" fill="none"/></svg></div><small>{data.slope<-.5?'Rising along the route':'Downhill along the route'}</small></div><div className={`ahead-instrument ${steeper?'steepening':''}`}><span>STEEPEST AHEAD · 100 M</span><strong>{steeper?'Steepening':data.ahead<Math.max(data.slope,0)-4?'Easing':'Similar pitch'} <b>{angle(data.ahead)}</b></strong><small>Approximate terrain angles · 30 m samples</small></div></div>
 <div className="descent-speed"><strong>{Math.round(data.speed*3.6)}</strong><span>KM/H</span><small>Arcade speed</small></div>
 <div className="descent-bottom"><div className="descent-progress"><span>{Math.round(data.progress*100)}% of route</span><span>{(data.remaining/1000).toFixed(1)} km to go</span><progress aria-label="Descent progress" value={data.progress} max={1}/></div><div className="descent-controls"><Button onClick={onPlay} disabled={data.finished}>{playing?'Pause':'Start / resume'}</Button><Button variant="secondary" aria-pressed={auto} onClick={onAuto}>Auto-follow {auto?'on':'off'}</Button><Button variant="ghost" onClick={onRestart}>Restart</Button></div><div className="descent-touch">{[['ArrowLeft','←','Steer left'],['ArrowRight','→','Steer right'],['ArrowDown','−','Slow down'],['ArrowUp','+','Speed up']].map(([key,label,name])=><Button key={key} variant="secondary" aria-label={name} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);onControl(key,true)}} onPointerUp={()=>onControl(key,false)} onPointerCancel={()=>onControl(key,false)} onLostPointerCapture={()=>onControl(key,false)} onKeyDown={e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();onControl(key,true)}}} onKeyUp={()=>onControl(key,false)} onBlur={()=>onControl(key,false)}>{label}</Button>)}</div><p>← → / A D steer · ↑ ↓ / W S speed · Space pause · Esc exit</p><small>Illustrative piste & markers. Angles describe the model, not route safety.</small></div>
 </div>
}
