'use client';
import {useEffect,useRef,useState} from 'react';
import {Orbit, Square} from 'lucide-react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {mountainSun} from '@/lib/sun';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {Sky} from 'three/addons/objects/Sky.js';
import {createMountainWeather} from './mountain-weather';
import {defaultAtmosphere,type AtmosphereSettings} from '@/lib/atmosphere';
import DescentHUD from './descent-hud';
import {addMatterhornWater} from './matterhorn-water';
import {addMatterhornBorder} from './matterhorn-border';
import {descentAngle,clamp,initialReadout,type DescentReadout} from '@/lib/descent';
import {places,type Place} from '@/lib/places';
import {buildTerrainGeometry,type TerrainManifest,type SurfaceManifest} from '@/lib/terrain-geometry';

export type MountainView='panorama'|'matterhorn'|'glacier'|'river'|'valley';
type Props={mountainView:MountainView;winterSurface:boolean;atmosphere:AtmosphereSettings;selected:Place;tab:string;view:number;day:string;minutes:number;routeVisible:boolean;pov:boolean;povPlaying:boolean;onPlayingChange:(playing:boolean)=>void;onExitPov:()=>void;onSelect:(p:Place)=>void;onStatus:(status:string)=>void;onProtect:()=>void};
type SceneAPI={orbit:()=>void;stopOrbit:()=>void;focus:(p:Place)=>void;overview:(view:MountainView)=>void;lighting:(day:string,minutes:number)=>void;routes:(visible:boolean)=>void;pov:(enabled:boolean)=>void;play:(playing:boolean)=>void;auto:(value:boolean)=>void;restart:()=>void;input:(key:string,down:boolean)=>void;filter:(tab:string,id:string)=>void};
const ORIGIN={lng:7.73,lat:46};
const location=(lng:number,lat:number,height:number)=>new THREE.Vector3((lng-ORIGIN.lng)*111320*Math.cos(ORIGIN.lat*Math.PI/180),height,(ORIGIN.lat-lat)*111320);
const noiseGLSL=`
float alpineHash(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
float alpineNoise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(alpineHash(i),alpineHash(i+vec3(1,0,0)),f.x),mix(alpineHash(i+vec3(0,1,0)),alpineHash(i+vec3(1,1,0)),f.x),f.y),mix(mix(alpineHash(i+vec3(0,0,1)),alpineHash(i+vec3(1,0,1)),f.x),mix(alpineHash(i+vec3(0,1,1)),alpineHash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float alpineFbm(vec3 p){return alpineNoise(p)*.53+alpineNoise(p*2.03)*.27+alpineNoise(p*4.11)*.13+alpineNoise(p*8.13)*.07;}
`;
function mountainMaterial(texture:THREE.Texture|null,winter:{value:number},detail:{map:{value:THREE.Texture|null};bounds:{value:THREE.Vector4};enabled:{value:number}}){const mat=new THREE.MeshStandardMaterial({color:0xffffff,map:texture,roughness:.94,metalness:0});mat.onBeforeCompile=shader=>{
 shader.uniforms.winterSurface=winter;shader.uniforms.detailMap=detail.map;shader.uniforms.detailBounds=detail.bounds;shader.uniforms.detailEnabled=detail.enabled;
 shader.vertexShader='attribute float skyVisibility; varying float vSkyVisibility; varying vec3 vLandPosition; varying vec3 vLandNormal;\n'+shader.vertexShader;
 shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvSkyVisibility = skyVisibility; vLandPosition = (modelMatrix * vec4(position, 1.0)).xyz; vLandNormal = normalize(mat3(modelMatrix)*normal);');
 shader.fragmentShader='varying float vSkyVisibility; uniform sampler2D detailMap; uniform vec4 detailBounds; uniform float detailEnabled; uniform float winterSurface; varying vec3 vLandPosition; varying vec3 vLandNormal;\n'+noiseGLSL+shader.fragmentShader;
 shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 vec3 p=vLandPosition;
 float longitude=7.73+p.x/(111320.*cos(radians(46.)));
 float latitude=radians(46.-p.z/111320.);
 vec2 merc=vec2((longitude+180.)/360.,(1.-log(tan(3.14159265*.25+latitude*.5))/3.14159265)*.5);
 vec2 duv=(merc-detailBounds.xy)/detailBounds.zw;duv.y=1.-duv.y;
 float detailMask=detailEnabled*smoothstep(0.,.015,duv.x)*smoothstep(0.,.015,duv.y)*(1.-smoothstep(.985,1.,duv.x))*(1.-smoothstep(.985,1.,duv.y));
 vec3 detailed=texture2D(detailMap,clamp(duv,0.,1.)).rgb;
 vec3 aerial=pow(mix(diffuseColor.rgb,detailed,detailMask),vec3(.78));vec3 terrainNormal=normalize(vLandNormal);
 float macro=alpineFbm(p*.004);float fine=alpineFbm(p*.18);float slope=clamp(terrainNormal.y,0.,1.);
 float strata=sin(p.y*.075+p.x*.012+alpineNoise(p*.016)*9.)*.5+.5;
 float fracture=pow(abs(sin(p.y*.17+p.z*.021+alpineNoise(p*.07)*4.)),5.);
 vec3 granite=mix(vec3(.19,.205,.22),vec3(.44,.425,.395),macro*.62+strata*.25+fine*.13);
 granite*=1.-fracture*.18;
 // The aerial mosaic provides geographic detail; snow is an explicitly modeled layer.
 #ifdef USE_MAP
 float aerialLuma=dot(aerial,vec3(.2126,.7152,.0722));
 granite=mix(granite,mix(vec3(aerialLuma),aerial,.78)*.86,.91);
 float forest=smoothstep(.006,.048,aerial.g-aerial.r)* (1.-smoothstep(2200.,2450.,p.y));
 #else
 float aerialLuma=.24;float forest=0.;
 #endif
 float snowLine=smoothstep(1650.,2600.,p.y+macro*240.);
 float snow=smoothstep(.53,.90,slope+(macro-.5)*.22)*snowLine;
 snow=max(snow,smoothstep(3000.,4100.,p.y)*smoothstep(.36,.78,slope)*.68);
 snow*=1.-forest*.83;
 float textureDetail=mix(.52,1.,smoothstep(.025,.52,aerialLuma));
 vec3 snowColor=mix(vec3(.58,.69,.78),vec3(.87,.92,.97),macro*.32+textureDetail*.68);
 snowColor*=mix(.94,1.,textureDetail);
 diffuseColor.rgb=mix(granite,snowColor,snow*winterSurface);
 
 `);
 shader.fragmentShader=shader.fragmentShader.replace('#include <aomap_fragment>', '#include <aomap_fragment>\nreflectedLight.indirectDiffuse *= mix(.38, 1., clamp(vSkyVisibility, 0., 1.));');
 // World-space microrelief changes lighting without moving measured ridge geometry.
 shader.fragmentShader=shader.fragmentShader.replace('#include <normal_fragment_maps>',`#include <normal_fragment_maps>
 float grain=alpineFbm(vLandPosition*.24);
 float rockRelief=alpineFbm(vLandPosition*vec3(.065,.19,.065))*1.4;
 float relief=mix(rockRelief*.4,grain*.075,snow*winterSurface);
 vec3 sigmaX=dFdx(vViewPosition),sigmaY=dFdy(vViewPosition);
 vec3 r1=cross(sigmaY,normal),r2=cross(normal,sigmaX);
 float determinant=dot(sigmaX,r1);
 vec3 gradient=sign(determinant)*(dFdx(relief)*r1+dFdy(relief)*r2);
 normal=normalize(abs(determinant)*normal-gradient);
 `);
 };return mat;}
export default function MountainScene({mountainView='panorama',winterSurface=true,atmosphere=defaultAtmosphere,selected,tab,view,day,minutes,routeVisible,pov,povPlaying,onPlayingChange,onExitPov,onSelect,onStatus,onProtect}:Props){
 const [orbiting,setOrbiting]=useState(false);
 const compass=useRef<HTMLDivElement>(null);const bearingLabel=useRef<HTMLSpanElement>(null);
 const winterUniform=useRef({value:winterSurface?1:0});winterUniform.current.value=winterSurface?1:0;
 const atmosphereRef=useRef(atmosphere);atmosphereRef.current=atmosphere;const container=useRef<HTMLDivElement>(null);const api=useRef<SceneAPI|null>(null);const callbacks=useRef({onSelect,onStatus,onPlayingChange,onExitPov,onProtect});callbacks.current={onSelect,onStatus,onPlayingChange,onExitPov,onProtect};const [readout,setReadout]=useState<DescentReadout>(initialReadout);const [autoFollow,setAutoFollow]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 useEffect(()=>{if(!container.current)return;let disposed=false,frame=0;const root=container.current;const scene=new THREE.Scene();scene.background=new THREE.Color('#b9cfdf');scene.fog=new THREE.FogExp2('#b6cbdc',.000035);let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});}catch{setError('3D graphics are unavailable in this browser.');setLoading(false);return}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setSize(root.clientWidth,root.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.06;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFShadowMap;renderer.shadowMap.autoUpdate=false;root.appendChild(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('aria-label','Ski descent keyboard controls');
 const camera=new THREE.PerspectiveCamera(43,root.clientWidth/root.clientHeight,10,400000);camera.position.set(10400,7600,-9500);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-300,2550,600);controls.enableDamping=true;controls.dampingFactor=.07;controls.minDistance=350;controls.maxDistance=22000;controls.maxPolarAngle=Math.PI*.43;controls.enablePan=true;controls.rotateSpeed=.5;controls.zoomSpeed=.75;
 const sky=new Sky();sky.scale.setScalar(180000);sky.material.depthWrite=false;sky.material.fragmentShader=sky.material.fragmentShader.replace('gl_FragColor = vec4( texColor, 1.0 );',`// Aerial camera views below the sea-level skydome horizon; use an Alpine color ramp.
 float aerialElevation=clamp((direction.y+.35)*1.5,0.,1.);
 vec3 alpineSky=mix(vec3(.24,.39,.58),vec3(.025,.09,.23),aerialElevation);
 vec3 eveningSky=mix(vec3(.61,.32,.20),vec3(.075,.12,.25),aerialElevation);
 float golden=1.-smoothstep(.015,.27,vSunDirection.y);
 vec3 skyColor=mix(alpineSky,eveningSky,golden*.78);
 skyColor*=mix(.055,1.,smoothstep(-.12,.05,vSunDirection.y));
 gl_FragColor = vec4(skyColor + L0 * .00004, 1.0);`);sky.material.uniforms.cloudCoverage.value=0;scene.add(sky);const sun=new THREE.DirectionalLight('#fff1db',3.3);sun.position.set(-13000,16000,-8000);sun.target.position.set(0,2400,0);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);sun.shadow.camera.left=-13000;sun.shadow.camera.right=13000;sun.shadow.camera.top=13000;sun.shadow.camera.bottom=-13000;sun.shadow.camera.near=100;sun.shadow.camera.far=45000;sun.shadow.normalBias=4;sun.shadow.bias=-.00004;scene.add(sun,sun.target);const hemisphere=new THREE.HemisphereLight('#c3d9f2','#6b6970',1.75);scene.add(hemisphere);
 const skyUniforms=sky.material.uniforms;skyUniforms.turbidity.value=2.3;skyUniforms.rayleigh.value=2.5;skyUniforms.mieCoefficient.value=.0015;skyUniforms.mieDirectionalG.value=.82;
 const pisteGroup=new THREE.Group();pisteGroup.visible=false;scene.add(pisteGroup);const routeGroup=new THREE.Group();scene.add(routeGroup);routeGroup.visible=routeVisible;
 function lighting(day:string,minutes:number){const pos=mountainSun(day,minutes),alt=THREE.MathUtils.degToRad(pos.altitude),az=THREE.MathUtils.degToRad(pos.azimuth);const direction=new THREE.Vector3(Math.sin(az)*Math.cos(alt),Math.sin(alt),-Math.cos(az)*Math.cos(alt));const warmth=1-THREE.MathUtils.smoothstep(pos.altitude,0,22);sun.position.copy(sun.target.position).addScaledVector(direction,25000);sun.color.copy(new THREE.Color('#fff4df').lerp(new THREE.Color('#ffaf71'),warmth));sun.intensity=pos.altitude<=0?0:3.1*THREE.MathUtils.smoothstep(pos.altitude,0,12);hemisphere.intensity=pos.altitude<0?.3:1.6;skyUniforms.sunPosition.value.copy(direction);skyUniforms.turbidity.value=1.8+warmth*1.4;scene.fog=new THREE.FogExp2(pos.altitude<0?'#67728b':warmth>.65?'#aab4ca':'#84a8c7',.000019);renderer.toneMappingExposure=1.05;renderer.shadowMap.needsUpdate=true;}lighting(day,minutes);
 let activeView:MountainView=mountainView;let waterGroup:THREE.Group|null=null;let pendingOverview:MountainView|null=null;
 let inPov=false,playing=false,progress=0,lastTick=0,speed=8,lateral=0,bank=0,lastHud=0,autoMode=false,ready=false;const held=new Set<string>();const reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
 const cockpit=new THREE.Group();cockpit.visible=false;cockpit.position.y=.18;camera.add(cockpit);scene.add(camera);
 const skiShape=new THREE.Shape();skiShape.moveTo(-.065,-.65);skiShape.lineTo(.065,-.65);skiShape.lineTo(.075,.45);skiShape.quadraticCurveTo(.07,.66,0,.7);skiShape.quadraticCurveTo(-.07,.66,-.075,.45);skiShape.closePath();
 const skiGeo=new THREE.ExtrudeGeometry(skiShape,{depth:.018,bevelEnabled:true,bevelSize:.006,bevelThickness:.006,bevelSegments:2,steps:1});skiGeo.rotateX(-Math.PI/2);
 for(const side of [-1,1]){const ski=new THREE.Mesh(skiGeo,new THREE.MeshStandardMaterial({color:'#264b5a',roughness:.36,depthTest:false,depthWrite:false}));ski.position.set(side*.19,-.71,-1.12);ski.rotation.y=-side*.035;ski.renderOrder=10;cockpit.add(ski);const stripe=new THREE.Mesh(new THREE.BoxGeometry(.028,.023,1.05),new THREE.MeshBasicMaterial({color:'#d9f388',depthTest:false,depthWrite:false}));stripe.position.set(side*.19,-.69,-1.12);stripe.rotation.y=-side*.035;stripe.renderOrder=11;cockpit.add(stripe)}
 const flecks=new Float32Array(80*3);for(let i=0;i<80;i++){flecks[i*3]=(Math.random()-.5)*5;flecks[i*3+1]=-1.4+Math.random();flecks[i*3+2]=-1-Math.random()*7}const sprayGeometry=new THREE.BufferGeometry();sprayGeometry.setAttribute('position',new THREE.BufferAttribute(flecks,3));const spray=new THREE.Points(sprayGeometry,new THREE.PointsMaterial({color:'#e7f6ff',size:.025,transparent:true,opacity:.3,depthWrite:false}));cockpit.add(spray);
 function input(key:string,down:boolean){if(down){if(playing&&!held.has(key)){if(key==='ArrowLeft'||key==='a'){if(!autoMode)lateral=clamp(lateral-.4,-6,6)}if(key==='ArrowRight'||key==='d'){if(!autoMode)lateral=clamp(lateral+.4,-6,6)}if(key==='ArrowUp'||key==='w')speed=clamp(speed+.5,3,18);if(key==='ArrowDown'||key==='s')speed=clamp(speed-.5,3,18);}held.add(key)}else held.delete(key)}
 function keyboard(event:KeyboardEvent,down:boolean){if(!inPov)return;const target=event.target as HTMLElement;if(target?.closest('input,textarea,select,[contenteditable=true]'))return;const key=event.key.length===1?event.key.toLowerCase():event.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','a','d','w','s'].includes(key)){event.preventDefault();input(key,down)}if(down&&!event.repeat&&key===' '&&!target?.closest('button')){event.preventDefault();callbacks.current.onPlayingChange(!playing)}if(down&&key==='Escape')callbacks.current.onExitPov()}
 const keyDown=(e:KeyboardEvent)=>keyboard(e,true),keyUp=(e:KeyboardEvent)=>keyboard(e,false);const blur=()=>{held.clear();if(inPov)callbacks.current.onPlayingChange(false)};const visibility=()=>{if(document.hidden)blur()};window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',visibility);
 const descentPoints:THREE.Vector3[]=[];const distances:number[]=[];let totalDistance=0;const savedCamera=camera.position.clone(),savedTarget=controls.target.clone();
 function pointAlong(distance:number,offset=0){if(descentPoints.length<2)return null;const d=THREE.MathUtils.clamp(distance,0,totalDistance);let i=1;while(i<distances.length-1&&distances[i]<d)i++;const t=(d-distances[i-1])/Math.max(.001,distances[i]-distances[i-1]);const point=descentPoints[i-1].clone().lerp(descentPoints[i],t);if(offset){const dir=descentPoints[i].clone().sub(descentPoints[i-1]);dir.y=0;dir.normalize();point.x+=-dir.z*offset;point.z+=dir.x*offset;}point.y=heightAt(point.x,point.z)+2.5;return point;}
 function setPov(enabled:boolean){if(enabled===inPov)return;stopOrbit();inPov=enabled;cockpit.visible=enabled;pisteGroup.visible=enabled;held.clear();transition=null;if(enabled){savedCamera.copy(camera.position);savedTarget.copy(controls.target);progress=0;lastTick=0;lateral=0;bank=0;speed=8;lastHud=0;camera.fov=72;renderer.domElement.focus({preventScroll:true});camera.near=.25;routeGroup.visible=false;controls.enabled=false;}else{camera.position.copy(savedCamera);controls.target.copy(savedTarget);camera.fov=43;camera.near=10;routeGroup.visible=routeVisible;controls.enabled=true;}camera.updateProjectionMatrix();root.dataset.pov=enabled?'yes':'no';}
 let tour:{start:number;target:THREE.Vector3;offset:THREE.Vector3}|null=null;
 function stopOrbit(){tour=null;setOrbiting(false);root.dataset.orbiting="no";}
 function startOrbit(){if(!ready||inPov)return;transition=null;const target=location(7.6586,45.9763,3350);const offset=camera.position.clone().sub(target);controls.target.copy(target);tour={start:performance.now(),target,offset};setOrbiting(true);root.dataset.orbiting="yes";}
 let pendingFocus:Place|null=null;const markers:{element:HTMLElement;point:THREE.Vector3;id:string;kind:string}[]=[];let transition:{start:number;from:THREE.Vector3;to:THREE.Vector3;targetFrom:THREE.Vector3;targetTo:THREE.Vector3}|null=null;
 function fly(target:THREE.Vector3,position:THREE.Vector3){stopOrbit();transition={start:performance.now(),from:camera.position.clone(),to:position,targetFrom:controls.target.clone(),targetTo:target}}
 let terrainPositions:Float32Array|null=null;let grid:{nx:number;nz:number;spacingX:number;spacingZ:number}|null=null;let originX=0,originZ=0;
 function heightAt(x:number,z:number){if(!grid||!terrainPositions)return 2300;const gx=THREE.MathUtils.clamp((x-originX)/grid.spacingX,0,grid.nx-1.001),gz=THREE.MathUtils.clamp((z-originZ)/grid.spacingZ,0,grid.nz-1.001);const ix=Math.floor(gx),iz=Math.floor(gz),u=gx-ix,v=gz-iz;const h=(dx:number,dz:number)=>terrainPositions![((iz+dz)*grid!.nx+ix+dx)*3+1];return u+v<=1?h(0,0)*(1-u-v)+h(1,0)*u+h(0,1)*v:h(1,1)*(u+v-1)+h(1,0)*(1-v)+h(0,1)*(1-u);}
 const weatherEffects=createMountainWeather(scene,camera,heightAt);
 api.current={orbit:startOrbit,stopOrbit,focus(p){stopOrbit();pendingOverview=null;activeView='panorama';if(waterGroup)waterGroup.visible=false;if(!ready){pendingFocus=p;return}const point=location(p.lng,p.lat,p.alt||2300);point.y=heightAt(point.x,point.z)+100;const offset=p.kind==='camera'?new THREE.Vector3(1700,1500,2300):new THREE.Vector3(500,600,800);fly(point,point.clone().add(offset))},overview(view){stopOrbit();pendingFocus=null;activeView=view;if(waterGroup)waterGroup.visible=['matterhorn','glacier','river'].includes(view);if(!ready){pendingOverview=view;return}const viewpoints={panorama:{target:new THREE.Vector3(-300,2550,600),eye:new THREE.Vector3(10400,7600,-9500)},matterhorn:{target:location(7.6586,45.9763,3350),eye:location(7.7075,46.020,5150)},glacier:{target:location(7.644,45.999,2650),eye:location(7.692,46.027,4100)},river:{target:location(7.7067,46.008,1970),eye:location(7.718,45.999,3200)},valley:{target:location(7.747,46.019,2150),eye:location(7.747,46.019,2150).add(new THREE.Vector3(1600,2400,-3600))}};const chosen=viewpoints[view]||viewpoints.panorama;fly(chosen.target,chosen.eye)},lighting,pov:setPov,play(value){playing=value;lastTick=0},auto(value){autoMode=value},input,restart(){progress=0;lateral=0;speed=8;bank=0;lastHud=0;held.clear();callbacks.current.onPlayingChange(false)},routes(visible){routeGroup.visible=visible&&!inPov},filter(t,id){for(const m of markers){m.element.classList.toggle('active',m.id===id);m.element.dataset.visible=t==='stories'?(m.kind==='camera'?'no':'yes'):(m.kind==='camera'?'yes':'no')}}};
 controls.addEventListener('start',()=>{transition=null;stopOrbit()});
 const stopTourKey=(event:KeyboardEvent)=>{if(event.key==='Escape'&&tour)stopOrbit()};window.addEventListener('keydown',stopTourKey);root.addEventListener('wheel',stopOrbit,{passive:true});
 const ac=new AbortController();
 let surfaceTexture:THREE.Texture|null=null;let detailTexture:THREE.Texture|null=null;const detail={map:{value:null as THREE.Texture|null},bounds:{value:new THREE.Vector4(0,0,1,1)},enabled:{value:0}};
 async function buildTerrain(){try{
 const texturePromise=new THREE.TextureLoader().loadAsync('/terrain/alpine-surface.webp').then(texture=>{if(disposed){texture.dispose();return null}surfaceTexture=texture;texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());return texture}).catch(()=>null);
 const responses=await Promise.all(['heights-hd.bin','manifest-hd.json','surface-manifest.json','sky-visibility.bin'].map(name=>fetch(`/terrain/${name}`,{signal:ac.signal})));
 if(responses.slice(0,3).some(r=>!r.ok))throw new Error('Terrain asset unavailable');
 const [hb,manifest,surface]=await Promise.all([responses[0].arrayBuffer(),responses[1].json() as Promise<TerrainManifest>,responses[2].json() as Promise<SurfaceManifest>]);
 if(disposed)return;const heights=new Float32Array(hb);const geometry=buildTerrainGeometry(heights,manifest,surface);const positions=geometry.getAttribute('position').array as Float32Array;
 let ambientSky=new Uint8Array(heights.length).fill(255);if(responses[3].ok){const baked=new Uint8Array(await responses[3].arrayBuffer());if(baked.length===heights.length)ambientSky=baked;}geometry.setAttribute('skyVisibility',new THREE.BufferAttribute(ambientSky,1,true));
 const texture=await texturePromise;if(disposed){geometry.dispose();return}
 const material=mountainMaterial(texture,winterUniform.current,detail);const mesh=new THREE.Mesh(geometry,material);mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);
 terrainPositions=positions;grid=manifest.grid;originX=manifest.bbox.min[0];originZ=manifest.bbox.min[2];
 void Promise.all([new THREE.TextureLoader().loadAsync('/terrain/matterhorn-detail.webp'),fetch('/terrain/matterhorn-detail.json',{signal:ac.signal}).then(r=>{if(!r.ok)throw new Error();return r.json() as Promise<{zoom:number;tileBounds:{minX:number;minY:number;maxX:number;maxY:number}}>})]).then(([tex,meta])=>{if(disposed){tex.dispose();return}detailTexture=tex;tex.colorSpace=THREE.SRGBColorSpace;tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());detail.map.value=tex;const n=2**meta.zoom,b=meta.tileBounds;detail.bounds.value.set(b.minX/n,b.minY/n,(b.maxX-b.minX+1)/n,(b.maxY-b.minY+1)/n);detail.enabled.value=1;root.dataset.matterhornDetail='loaded'}).catch(()=>{root.dataset.matterhornDetail='unavailable'});
 try{waterGroup=await addMatterhornWater(scene,root,heightAt,location,markers,ac.signal,()=>callbacks.current.onProtect());void addMatterhornBorder(waterGroup,heightAt,location,ac.signal).then(()=>{if(!disposed)root.dataset.border="loaded"}).catch(()=>{});waterGroup.visible=['matterhorn','glacier','river'].includes(activeView);}catch{if(disposed)return}
 root.dataset.terrainVertices=String(heights.length);root.dataset.surface=texture?'swissimage':'procedural-fallback';
 
 const routes=await (await fetch('/terrain/routes.geojson',{signal:ac.signal})).json() as {features:{geometry:{coordinates:number[][]}}[]};if(disposed)return;
 for(const feature of routes.features){const coords=feature.geometry.coordinates as number[][];const points:THREE.Vector3[]=[];for(let i=0;i<coords.length-1;i++){const a=location(coords[i][0],coords[i][1],0),b=location(coords[i+1][0],coords[i+1][1],0);const steps=Math.ceil(a.distanceTo(b)/12);for(let j=0;j<steps;j++){const q=a.clone().lerp(b,j/steps);q.y=heightAt(q.x,q.z)+12;points.push(q)}}const end=coords[coords.length-1],q=location(end[0],end[1],0);q.y=heightAt(q.x,q.z)+12;points.push(q);for(const point of points){if(descentPoints.length&&point.distanceTo(descentPoints[descentPoints.length-1])<.01)continue;if(descentPoints.length)totalDistance+=point.distanceTo(descentPoints[descentPoints.length-1]);descentPoints.push(point.clone());distances.push(totalDistance);}const curve=new THREE.CurvePath<THREE.Vector3>();for(let i=1;i<points.length;i++)curve.add(new THREE.LineCurve3(points[i-1],points[i]));const route=new THREE.Mesh(new THREE.TubeGeometry(curve,points.length*2,9,5,false),new THREE.MeshBasicMaterial({color:'#ff9854',fog:false}));routeGroup.add(route);}
 // Illustrative piste width, grooming and markers are visual guides, not surveyed infrastructure.
 const vertices:number[]=[],uvs:number[]=[],faces:number[]=[];const centerVertices:number[]=[],centerFaces:number[]=[];
 const rows=Math.ceil(totalDistance/2);const width=9,cols=12;
 const poleGeometry=new THREE.CylinderGeometry(.065,.085,2.5,6);poleGeometry.translate(0,1.25,0);
 const poleMaterial=new THREE.MeshStandardMaterial({color:'#c94b35',roughness:.65});
 const capGeometry=new THREE.SphereGeometry(.16,6,4);const capMaterial=new THREE.MeshBasicMaterial({color:'#ffba61'});
 for(let row=0;row<=rows;row++){const d=Math.min(row*2,totalDistance),p=pointAlong(d)!,ahead=pointAlong(Math.min(d+3,totalDistance))!,behind=pointAlong(Math.max(0,d-3))!;const tangent=ahead.sub(behind);tangent.y=0;tangent.normalize();const side=new THREE.Vector3(-tangent.z,0,tangent.x);
 for(let col=0;col<=cols;col++){const offset=(col/cols*2-1)*width;const q=p.clone().addScaledVector(side,offset);vertices.push(q.x,heightAt(q.x,q.z)+.65,q.z);uvs.push(offset,d);if(row<rows&&col<cols){const i=row*(cols+1)+col;faces.push(i,i+cols+1,i+1,i+1,i+cols+1,i+cols+2)}}
 if(row%20===0)for(const sign of [-1,1]){const q=p.clone().addScaledVector(side,sign*width);q.y=heightAt(q.x,q.z);const pole=new THREE.Mesh(poleGeometry,poleMaterial);pole.position.copy(q);pole.castShadow=true;pisteGroup.add(pole);const cap=new THREE.Mesh(capGeometry,capMaterial);cap.position.copy(q).add(new THREE.Vector3(0,2.45,0));pisteGroup.add(cap)}
 if(row%60===20){const arrow=new THREE.BufferGeometry();const av:number[]=[];for(const [forward,across] of [[2,0],[-1.6,-1.3],[-.6,0],[-1.6,1.3]]){const q=p.clone().addScaledVector(tangent,forward).addScaledVector(side,across);av.push(q.x,heightAt(q.x,q.z)+.8,q.z)}arrow.setAttribute('position',new THREE.Float32BufferAttribute(av,3));arrow.setIndex([0,1,2,0,2,3]);pisteGroup.add(new THREE.Mesh(arrow,new THREE.MeshBasicMaterial({color:'#e6b47b',side:THREE.DoubleSide})));}
 // Short dashes, sized for skier height rather than the aerial map's thick route tube.
 if(row<rows&&row%10<5){const next=pointAlong(Math.min(d+2,totalDistance))!;const base=centerVertices.length/3;for(const [pnt,offset] of [[p,-.12],[p,.12],[next,-.12],[next,.12]] as [THREE.Vector3,number][]){const q=pnt.clone().addScaledVector(side,offset);centerVertices.push(q.x,heightAt(q.x,q.z)+.73,q.z)}centerFaces.push(base,base+2,base+1,base+1,base+2,base+3)}
 }
 const pisteGeometry=new THREE.BufferGeometry();pisteGeometry.setAttribute('position',new THREE.Float32BufferAttribute(vertices,3));pisteGeometry.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));pisteGeometry.setIndex(faces);pisteGeometry.computeVertexNormals();
 const pisteMaterial=new THREE.MeshStandardMaterial({color:'#c0d3df',roughness:.88,side:THREE.DoubleSide,polygonOffset:true,polygonOffsetFactor:-1});
 pisteMaterial.onBeforeCompile=shader=>{shader.vertexShader='varying vec2 vPisteUV;\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvPisteUV=uv;');shader.fragmentShader='varying vec2 vPisteUV;\n'+shader.fragmentShader;shader.fragmentShader=shader.fragmentShader.replace('#include <color_fragment>',`#include <color_fragment>
 float fade=1.-smoothstep(12.,65.,length(vViewPosition));float groom=sin(vPisteUV.x*42.)*.035*fade;float crossTrack=sin(vPisteUV.y*.65)*.018;diffuseColor.rgb*=.94+groom+crossTrack;
 `)};
 const piste=new THREE.Mesh(pisteGeometry,pisteMaterial);piste.receiveShadow=true;pisteGroup.add(piste);
 const dashGeometry=new THREE.BufferGeometry();dashGeometry.setAttribute('position',new THREE.Float32BufferAttribute(centerVertices,3));dashGeometry.setIndex(centerFaces);const dashes=new THREE.Mesh(dashGeometry,new THREE.MeshBasicMaterial({color:'#cf733c',side:THREE.DoubleSide}));pisteGroup.add(dashes);
 // Vegetation is an illustrative reconstruction, not a surveyed tree inventory.
 const waterBounds=waterGroup?.userData.waterBounds as {minX:number;maxX:number;minZ:number;maxZ:number}|undefined;
 const normals=geometry.getAttribute('normal');const candidates:number[]=[];for(let i=0;i<positions.length/3;i++){const y=positions[i*3+1];if(y>1700&&y<2270&&normals.getY(i)>.7&&!(waterBounds&&positions[i*3]>=waterBounds.minX&&positions[i*3]<=waterBounds.maxX&&positions[i*3+2]>=waterBounds.minZ&&positions[i*3+2]<=waterBounds.maxZ)&&Math.sin(i*127.1)*43758.5453%1>.65)candidates.push(i)}
 const count=Math.min(2600,candidates.length);const tiers:THREE.BufferGeometry[]=[];
 for(let tier=0;tier<5;tier++){const geo=new THREE.ConeGeometry(4.8-tier*.82,7-tier*.5,9,1);geo.translate(0,5+tier*3.1,0);tiers.push(geo)}
 const foliageGeo=mergeGeometries(tiers);tiers.forEach(g=>g.dispose());
 const foliageMat=new THREE.MeshStandardMaterial({color:'#6e827d',roughness:.96});const trees=new THREE.InstancedMesh(foliageGeo,foliageMat,count);const dummy=new THREE.Object3D();
 for(let j=0;j<count;j++){const i=candidates[Math.floor(j*candidates.length/count)];dummy.position.set(positions[i*3],positions[i*3+1],positions[i*3+2]);const scale=.65+(Math.sin(i)*.5+.5)*.65;dummy.scale.setScalar(scale);dummy.rotation.y=i*.73;dummy.updateMatrix();trees.setMatrixAt(j,dummy.matrix);trees.setColorAt(j,new THREE.Color().setHSL(.40,.13,.40+(i%10)*.013))}trees.castShadow=true;trees.receiveShadow=true;scene.add(trees);
 // Small architectural accents indicate the hamlet; individual buildings are illustrative.
 const hamlet=location(7.7689,46.0125,2100);const wall=new THREE.MeshStandardMaterial({color:'#503d30',roughness:1});const roof=new THREE.MeshStandardMaterial({color:'#e3e9ed',roughness:.85});for(let j=0;j<12;j++){const x=hamlet.x+Math.sin(j*2.4)*80,z=hamlet.z+Math.cos(j*1.6)*100;const group=new THREE.Group();group.position.set(x,heightAt(x,z),z);const body=new THREE.Mesh(new THREE.BoxGeometry(12,9,17),wall);body.position.y=4.5;body.castShadow=true;body.receiveShadow=true;group.add(body);const cap=new THREE.Mesh(new THREE.ConeGeometry(12,6,4),roof);cap.rotation.y=Math.PI/4;cap.scale.z=1.3;cap.position.y=11.5;cap.castShadow=true;group.add(cap);const trim=new THREE.MeshStandardMaterial({color:'#302a25',roughness:1});const glass=new THREE.MeshStandardMaterial({color:'#a7bcc8',roughness:.2,metalness:.25});
 for(let level=0;level<6;level++){const beam=new THREE.Mesh(new THREE.BoxGeometry(12.4,.2,17.4),trim);beam.position.y=1+level*1.3;group.add(beam)}
 for(const side of [-1,1])for(const wx of [-3.5,3.5]){const frame=new THREE.Mesh(new THREE.BoxGeometry(2.2,2.6,.24),trim);frame.position.set(wx,5,side*8.6);group.add(frame);const window=new THREE.Mesh(new THREE.PlaneGeometry(1.6,1.9),glass);window.position.set(wx,5,side*8.75);if(side<0)window.rotation.y=Math.PI;group.add(window)}
 const chimney=new THREE.Mesh(new THREE.BoxGeometry(1.4,5,1.4),trim);chimney.position.set(3,12,2);chimney.castShadow=true;group.add(chimney);group.rotation.y=j*.8;scene.add(group)}
 for(const p of places){const point=location(p.lng,p.lat,p.alt||2300);point.y=heightAt(point.x,point.z)+85;const button=document.createElement('button');button.className=`pin scene-pin ${p.kind}`;button.dataset.visible=p.kind==='camera'?'yes':'no';button.setAttribute('aria-label',`Explore ${p.name}`);const dot=document.createElement('span');dot.className='pin-dot';button.appendChild(dot);button.appendChild(document.createTextNode(p.short));button.onclick=()=>callbacks.current.onSelect(p);root.appendChild(button);markers.push({element:button,point,id:p.id,kind:p.kind})}
 const peak=document.createElement('button');peak.className='peak-label scene-pin';peak.innerHTML='<span>MATTERHORN / CERVINO</span><small>4,478 m · Swiss–Italian border</small>';peak.setAttribute('aria-label','View Matterhorn');const mp=location(7.6586,45.9763,4560);peak.onclick=()=>fly(location(7.6586,45.9763,3400),location(7.6586,45.9763,3400).add(new THREE.Vector3(6500,2000,-6000)));root.appendChild(peak);markers.push({element:peak,point:mp,id:'matterhorn',kind:'peak'});peak.dataset.visible='yes';
 ready=true;if(pendingOverview){api.current?.overview(pendingOverview);pendingOverview=null}if(pendingFocus){api.current?.focus(pendingFocus);api.current?.filter(pendingFocus.kind==='camera'?'now':'stories',pendingFocus.id);pendingFocus=null}renderer.shadowMap.needsUpdate=true;setLoading(false);callbacks.current.onStatus(surfaceTexture?'Swiss terrain + aerial mosaic':'Swiss terrain · aerial surface unavailable');
 }catch(e){if(!disposed){setLoading(false);setError(e instanceof Error?e.message:'Mountain geometry could not load.')}}}void buildTerrain();
 const resize=new ResizeObserver(()=>{if(!root.clientWidth||!root.clientHeight)return;renderer.setSize(root.clientWidth,root.clientHeight);camera.aspect=root.clientWidth/root.clientHeight;camera.updateProjectionMatrix()});resize.observe(root);const projected=new THREE.Vector3(),forward=new THREE.Vector3();let lastCompass=0;
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);if(tour){const t=Math.min(1,(now-tour.start)/10000),ease=t*t*(3-2*t);const offset=tour.offset.clone().applyAxisAngle(new THREE.Vector3(0,1,0),ease*.70);camera.position.copy(tour.target).add(offset);camera.position.y=Math.max(camera.position.y,heightAt(camera.position.x,camera.position.z)+550);controls.target.copy(tour.target);if(t===1)stopOrbit();}if(transition){const t=Math.min((now-transition.start)/2100,1),s=t*t*(3-2*t);camera.position.lerpVectors(transition.from,transition.to,s);controls.target.lerpVectors(transition.targetFrom,transition.targetTo,s);if(t===1)transition=null}controls.target.x=THREE.MathUtils.clamp(controls.target.x,-9200,7500);controls.target.z=THREE.MathUtils.clamp(controls.target.z,-7500,6000);if(inPov&&ready){const dt=lastTick?Math.min((now-lastTick)/1000,.08):0;lastTick=now;
 const finished=progress>=totalDistance;const moving=playing&&!finished;
 const steer=Number(held.has('ArrowRight')||held.has('d'))-Number(held.has('ArrowLeft')||held.has('a'));
 if(moving){const throttle=Number(held.has('ArrowUp')||held.has('w'))-Number(held.has('ArrowDown')||held.has('s'));speed=clamp(speed+throttle*dt*4,3,18);lateral=autoMode?THREE.MathUtils.damp(lateral,0,3,dt):clamp(lateral+steer*dt*3.8,-6,6);progress=Math.min(totalDistance,progress+dt*speed);}
 const eye=pointAlong(progress,lateral),look=pointAlong(Math.min(progress+22,totalDistance),lateral);
 if(eye&&look){camera.position.copy(eye);if(progress+22>=totalDistance){const behind=pointAlong(Math.max(0,totalDistance-22),lateral);if(behind)look.copy(eye).add(eye.clone().sub(behind));}look.y=Math.max(look.y,eye.y-10);camera.rotateZ(-bank);const previousRotation=camera.quaternion.clone();camera.lookAt(look);if(moving&&dt>0&&!reducedMotion){const targetRotation=camera.quaternion.clone();camera.quaternion.copy(previousRotation).slerp(targetRotation,1-Math.exp(-dt*7));}
 bank=THREE.MathUtils.damp(bank,moving&&!autoMode&&!reducedMotion?-steer*.035:0,5,dt);camera.rotateZ(bank);cockpit.rotation.z=-bank*.5;
 spray.visible=moving&&!reducedMotion;const sprayMaterial=spray.material as THREE.PointsMaterial;sprayMaterial.opacity=Math.min(.3,speed*.016);if(spray.visible){for(let i=0;i<80;i++){flecks[i*3+2]+=dt*speed*.45;if(flecks[i*3+2]>-.5)flecks[i*3+2]=-8;}sprayGeometry.attributes.position.needsUpdate=true;}
 root.dataset.lateralOffset=lateral.toFixed(2);root.dataset.arcadeSpeed=speed.toFixed(2);root.dataset.descentProgress=String(Math.round(progress/Math.max(1,totalDistance)*100));
 if(now-lastHud>150){const a=pointAlong(Math.max(0,progress-15),lateral)!,b=pointAlong(Math.min(totalDistance,progress+15),lateral)!;const slope=descentAngle(a,b);let ahead=-90;for(let step=20;step<=100;step+=20){const start=pointAlong(Math.min(totalDistance,progress+step))!,end=pointAlong(Math.min(totalDistance,progress+step+30))!;ahead=Math.max(ahead,descentAngle(start,end));}setReadout({slope,ahead:Math.max(0,ahead),speed:moving?speed:0,progress:progress/totalDistance,remaining:totalDistance-progress,offset:lateral,finished:progress>=totalDistance});lastHud=now;}
 if(progress>=totalDistance&&playing)callbacks.current.onPlayingChange(false);
 }
}else{lastTick=0;controls.update();camera.position.y=Math.max(camera.position.y,heightAt(camera.position.x,camera.position.z)+250);}if(now-lastCompass>120){camera.getWorldDirection(forward);if(Math.hypot(forward.x,forward.z)>.001){const heading=(THREE.MathUtils.radToDeg(Math.atan2(forward.x,-forward.z))+360)%360;compass.current?.style.setProperty('--bearing',`${heading}deg`);const label=`${['N','NE','E','SE','S','SW','W','NW'][Math.round(heading/45)%8]} ${Math.round(heading)%360}°`;if(bearingLabel.current)bearingLabel.current.textContent=label;compass.current?.setAttribute('aria-label',`Camera facing ${label}. North, east, south and west rotate with the view.`);root.dataset.heading=String(Math.round(heading)%360)}lastCompass=now;}weatherEffects.update(now,atmosphereRef.current,inPov);root.dataset.windFrom=String(atmosphereRef.current.windFrom);root.dataset.snowIntensity=String(atmosphereRef.current.snow);renderer.render(scene,camera);const occupied:{x:number;y:number;w:number}[]=[];for(const m of [...markers].sort((a,b)=>Number(b.element.classList.contains("active"))-Number(a.element.classList.contains("active")))){projected.copy(m.point).project(camera);const isWater=m.kind==='water'||m.kind==='glacier';let show=!inPov&&(isWater?['matterhorn','glacier','river'].includes(activeView):(m.element.dataset.visible==='yes'||m.kind==='peak'))&&projected.z<1&&projected.z>-1&&Math.abs(projected.x)<1.05&&Math.abs(projected.y)<1.05;const sx=(projected.x*.5+.5)*root.clientWidth,sy=(-projected.y*.5+.5)*root.clientHeight,w=m.element.offsetWidth||110;if(occupied.some(o=>Math.abs(o.x-sx)<(o.w+w)/2+12&&Math.abs(o.y-sy)<46))show=false;if(root.closest('.astra-open')){if(sy<75&&sx<180)show=false}else{if(sy<190&&sx<330)show=false;if(sy<190&&sx>root.clientWidth-370)show=false}if(show)occupied.push({x:sx,y:sy,w});m.element.style.visibility=show?'visible':'hidden';if(show)m.element.style.transform=`translate(-50%,-100%) translate(${(projected.x*.5+.5)*root.clientWidth}px,${(-projected.y*.5+.5)*root.clientHeight}px)`}}frame=requestAnimationFrame(animate);
 return()=>{disposed=true;window.removeEventListener('keydown',stopTourKey);root.removeEventListener('wheel',stopOrbit);weatherEffects.dispose();window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',visibility);ac.abort();surfaceTexture?.dispose();detailTexture?.dispose();cancelAnimationFrame(frame);resize.disconnect();controls.dispose();api.current=null;scene.traverse(obj=>{const mesh=obj as THREE.Mesh;if(mesh.geometry)mesh.geometry.dispose();if(mesh.material){for(const material of Array.isArray(mesh.material)?mesh.material:[mesh.material])material.dispose()}});renderer.dispose();root.replaceChildren()};
 // Scene initialization is stable; changing controls uses the API below.
 },[]);
 useEffect(()=>{api.current?.pov(pov)},[pov]);useEffect(()=>{api.current?.auto(autoFollow)},[autoFollow]);useEffect(()=>{api.current?.play(povPlaying)},[povPlaying]);const initial=useRef(true);useEffect(()=>{if(initial.current){initial.current=false;return}api.current?.focus(selected)},[selected]);useEffect(()=>{if(view)api.current?.overview(mountainView)},[view]);useEffect(()=>{api.current?.lighting(day,minutes)},[day,minutes]);useEffect(()=>{api.current?.routes(routeVisible)},[routeVisible]);useEffect(()=>{api.current?.filter(tab,selected.id)},[tab,selected]);
 return <><div className="custom-scene" ref={container}/>{mountainView==='matterhorn'&&!pov&&<button className="mountain-orbit" disabled={loading||!!error} onClick={()=>orbiting?api.current?.stopOrbit():api.current?.orbit()} aria-label={orbiting?'Stop Matterhorn orbit':'Play 10-second Matterhorn orbit'}>{orbiting?<Square size={14}/>:<Orbit size={16}/>}<span>{orbiting?'Stop orbit':'Orbit the Matterhorn'}<small>{orbiting?'Drag or Esc to stop':'10-second view'}</small></span></button>}<aside className="mountain-orientation" aria-label="Mountain orientation"><div className="mountain-compass" ref={compass} role="img" aria-label="Compass loading"><div className="compass-rose"><span className="compass-n">N</span><span className="compass-e">E</span><span className="compass-s">S</span><span className="compass-w">W</span><i/></div><span className="compass-bearing" ref={bearingLabel}>—</span></div><div className="country-context"><span><b aria-hidden="true">🇨🇭</b> Switzerland</span><span><b aria-hidden="true">🇮🇹</b> Italy</span><a href="https://www.openstreetmap.org/way/1248126041" target="_blank" rel="noreferrer"><i/>Swiss–Italian border ↗</a><small>Zermatt is in Switzerland</small></div></aside>{pov&&<DescentHUD data={readout} playing={povPlaying} auto={autoFollow} onAuto={()=>setAutoFollow(v=>!v)} onPlay={()=>onPlayingChange(!povPlaying)} onRestart={()=>api.current?.restart()} onExit={onExitPov} onControl={(key,down)=>api.current?.input(key,down)}/>}{loading&&<div className="map-loading"><span>Shaping the Swiss Alps</span><small>Swiss terrain · aerial surface detail</small></div>}{error&&<div className="scene-error">{error}. Reload to retry.</div>}</>
}
