'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as MapType,Marker} from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import {places,type Place} from '@/lib/places';
let terrainPromise:Promise<any>|null=null;
export default function MountainMap({selected,tab,view,onSelect,onStatus}:{selected:Place;tab:string;view:number;onSelect:(p:Place)=>void;onStatus:(status:string)=>void}){
 const element=useRef<HTMLDivElement>(null);const map=useRef<MapType|null>(null);const pins=useRef<{place:Place;marker:Marker;button:HTMLButtonElement}[]>([]);const choose=useRef(onSelect);choose.current=onSelect;const report=useRef(onStatus);report.current=onStatus;const [ready,setReady]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let disposed=false;let instance:MapType|undefined;
 async function init(){try{const ml=await import('maplibre-gl');if(disposed||!element.current)return;
 instance=new ml.Map({container:element.current,style:{version:8,sources:{aerial:{type:'raster',tiles:['https://wmts.geo.admin.ch/1.0.0/ch.swisstopo.swissimage/default/current/3857/{z}/{x}/{y}.jpeg'],tileSize:256,maxzoom:19,attribution:'© swisstopo · Aerial imagery, not current snow'}},layers:[{id:'background',type:'background',paint:{'background-color':'#8baabf'}},{id:'aerial',type:'raster',source:'aerial',paint:{'raster-saturation':-.15,'raster-contrast':.08}}]},center:[7.778,46.012],zoom:12.2,pitch:64,bearing:205,maxPitch:80,minZoom:10,maxZoom:17,canvasContextAttributes:{antialias:true},attributionControl:{compact:true}});map.current=instance;
 instance.on('load',async()=>{if(disposed||!instance)return;setReady(true);
 for(const p of places){const el=document.createElement('button');el.className=`pin ${p.kind==='food'?'food':p.kind==='culture'?'culture':''}`;el.setAttribute('aria-label',`Explore ${p.name}`);const dot=document.createElement('span');dot.className='pin-dot';el.appendChild(dot);el.appendChild(document.createTextNode(p.short));el.onclick=()=>choose.current(p);const marker=new ml.Marker({element:el,anchor:'bottom'}).setLngLat([p.lng,p.lat]).addTo(instance);pins.current.push({place:p,marker,button:el})}
 try{const [{loadQuantizedMeshDataset,registerQuantizedMeshTerrain},{default:decode}]=await Promise.all([import('maplibre-gl-3dtiles-terrain'),import('@here/quantized-mesh-decoder')]);terrainPromise??=loadQuantizedMeshDataset('https://3d.geo.admin.ch/ch.swisstopo.terrain.3d/v1/layer.json',{attribution:'Terrain: © swisstopo',boundsOverride:{west:5.6,south:45.5,east:11,north:48.2},maxZoom:14}).catch((e:unknown)=>{terrainPromise=null;throw e});const dataset=await terrainPromise;if(disposed||!instance)return;const {sourceSpec}=registerQuantizedMeshTerrain(ml,{dataset,decode});instance.addSource('terrain',sourceSpec);instance.setTerrain({source:'terrain',exaggeration:1});}catch{if(!disposed){report.current('Aerial imagery · terrain unavailable');setError('Terrain could not load. The aerial map remains available. Reload the page to retry.')} }});
 instance.on('sourcedata',e=>{if(!disposed&&e.sourceId==='terrain'&&e.isSourceLoaded)report.current('3D terrain · aerial imagery')});instance.on('error',e=>{if(!disposed&&(e as unknown as {sourceId?:string}).sourceId==='terrain'){report.current('Aerial imagery · terrain incomplete');setError('Some terrain tiles could not load. Reload the page to retry.')}if(!disposed&&e.error?.message?.includes('WebGL'))setError('Your browser could not start 3D graphics. Explore the places and camera views alongside the map.')});
 }catch{if(!disposed)setError('The 3D map could not start. You can still explore the cameras and stories.')}}void init();return()=>{disposed=true;pins.current=[];instance?.remove();map.current=null}},[]);
 useEffect(()=>{if(!ready)return;pins.current.forEach(({place,button})=>{button.classList.toggle('active',place.id===selected.id);button.style.display=tab==='stories'?(place.kind==='camera'?'none':'flex'):(place.kind==='camera'?'flex':'none')});if(map.current)map.current.flyTo({center:[selected.lng,selected.lat],zoom:selected.kind==='camera'?13.1:15.3,pitch:62,bearing:205,duration:1800,essential:false})},[selected,tab,ready]);
 useEffect(()=>{if(view&&map.current)map.current.flyTo({center:[7.778,46.012],zoom:12.2,pitch:64,bearing:205,duration:1800,essential:false})},[view]);
 return <><div className="map-root" ref={element}/>{!ready&&!error&&<div className="map-loading"><span>Loading the Swiss Alps</span><small>Real terrain · swisstopo</small></div>}{error&&<div className="scene-error">{error}<br/><a href="https://map.geo.admin.ch/" target="_blank" rel="noreferrer">Open the Swiss map</a></div>}</>
}
