'use client';
import {Wind,Snowflake,Pause,Play} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {weatherTime,type WeatherReading} from '@/lib/weather';
import {Button} from '@/components/ui/button';
import {Slider} from '@/components/ui/slider';
import {compass,snowLabel,type AtmosphereSettings} from '@/lib/atmosphere';
type Props={value:AtmosphereSettings;onChange:(v:AtmosphereSettings)=>void;mode:'data'|'custom';onMode:(mode:'data'|'custom')=>void;reading:WeatherReading|null;loading:boolean;error:string;location:string;onRefresh:()=>void};
export default function WeatherControls({value,onChange,mode,onMode,reading,loading,error,location,onRefresh}:Props){
 const set=(v:Partial<AtmosphereSettings>)=>onChange({...value,...v});
 return <div className="weather-controls"><Tabs value={mode} onValueChange={v=>onMode(v as 'data'|'custom')}><TabsList className="weather-mode-tabs"><TabsTrigger value="data">Weather data</TabsTrigger><TabsTrigger value="custom">Custom</TabsTrigger></TabsList></Tabs>{mode==='data'?<div className="weather-provenance"><strong>{location}</strong>{reading?<><span>Open-Meteo · weather-model estimate</span><span>{weatherTime(reading.time)} · Europe/Zurich</span><span>Wind at 10 m above ground{reading.place.elevation?` · ${reading.place.elevation.toLocaleString()} m elevation`:''}</span><a href={reading.source.url} target="_blank" rel="noreferrer">Source & method ↗</a><span>Grid: {reading.grid.latitude.toFixed(3)}° N, {reading.grid.longitude.toFixed(3)}° E</span></>:<span role="status">{loading?'Fetching wind and snowfall…':error||'Weather data unavailable.'}</span>}<Button variant="ghost" disabled={loading} onClick={onRefresh}>{loading?'Refreshing…':'Refresh data'}</Button><span>Refreshes every 5 minutes while open.</span></div>:<div className="weather-scenario">CUSTOM SCENARIO · NOT WEATHER DATA</div>}<div className="weather-control-heading"><span><Wind size={17}/>Wind speed</span><strong>{mode==='data'&&!reading?'—':value.windKmh.toFixed(1)} <small>km/h</small></strong></div><Slider aria-label="Simulated wind speed" disabled={mode==='data'} min={0} max={Math.max(80,Math.ceil(value.windKmh/10)*10)} step={mode==='data'?.1:5} value={[value.windKmh]} onValueChange={v=>set({windKmh:Array.isArray(v)?v[0]:v})}/><div className="sun-hours"><span>Calm</span><span>{Math.max(80,Math.ceil(value.windKmh/10)*10)} km/h</span></div>
 <div className="weather-control-heading"><span>Wind from</span><strong>{mode==='data'&&!reading?'—':compass(value.windFrom)} <small>{mode==='data'&&!reading?'':`${value.windFrom}°`}</small></strong></div><Slider aria-label="Simulated wind direction" disabled={mode==='data'} min={0} max={360} step={mode==='data'?1:15} value={[value.windFrom]} onValueChange={v=>set({windFrom:Array.isArray(v)?v[0]:v})}/><div className="sun-hours"><span>N</span><span>E</span><span>S</span><span>W</span><span>N</span></div>
 <div className="weather-control-heading"><span><Snowflake size={17}/>Snowfall</span><strong>{mode==='data'?(reading?`${reading.snowfallCm} cm`:'—'):snowLabel(value.snow)}</strong></div><Slider aria-label="Simulated snowfall intensity" disabled={mode==='data'} min={0} max={100} step={mode==='data'?.01:5} value={[value.snow]} onValueChange={v=>set({snow:Array.isArray(v)?v[0]:v})}/>{mode==='data'?<div className="weather-snow-interval">{reading?`Modeled snowfall in the preceding ${reading.intervalSeconds/60} minutes. Gusts: ${reading.gusts.toFixed(1)} km/h.`:'Snowfall unknown; flakes are off.'}</div>:<div className="sun-hours"><span>Off</span><span>Heavy</span></div>}
 <label className="weather-traces"><input type="checkbox" checked={value.traces} onChange={e=>set({traces:e.target.checked})}/> Show wind traces</label>
 <div className="weather-actions">{mode==='custom'&&<><Button variant="secondary" onClick={()=>set({windKmh:25,windFrom:315,snow:45,traces:true,paused:false})}>Snow flurry</Button><Button variant="ghost" onClick={()=>set({windKmh:0,snow:0})}>Clear</Button></>}<Button variant="ghost" size="icon" aria-label={value.paused?'Play weather animation':'Pause weather animation'} onClick={()=>set({paused:!value.paused})}>{value.paused?<Play size={15}/>:<Pause size={15}/>}</Button></div>
 <p className="weather-limits">Particles illustrate the data; snowfall density is a visual scale. Terrain snow cover remains illustrative. No airflow or accumulation forecast.</p><p className="weather-limits">{mode==='data'?'Weather data uses the timestamp above, independently of the Sun simulation date.':'Custom settings are independent of weather data.'} Overview motion is exaggerated for visibility.</p></div>
}
