export type Place = {id:string;name:string;short:string;kind:'camera'|'culture'|'food';lng:number;lat:number;alt?:number;story:string;source:string;camera?:string};
export const places:Place[]=[
{id:'rothorn',name:'Rothorn panorama',short:'Rothorn',kind:'camera',lng:7.797409,lat:46.021509,alt:3103,story:'A balcony above Zermatt. Rothorn looks across to the Matterhorn and the surrounding four-thousand-metre peaks. In winter, this is the start of descents toward Blauherd and Sunnegga; in summer, a place to pause above the valley.',source:'https://www.matterhornparadise.ch/en/experience/peaks/rothorn',camera:'https://zbag.roundshot.com/rothorn/'},
{id:'blauherd',name:'Blauherd plateau',short:'Blauherd',kind:'camera',lng:7.786053,lat:46.016699,alt:2571,story:'Between Sunnegga and Rothorn, a sunny plateau opens toward the Matterhorn. Its wooden heart frames a familiar photograph, and the Five Lakes Trail starts nearby. Winter ski routes share this landscape with summer trails and Alpine wildlife.',source:'https://www.matterhornparadise.ch/en/experience/peaks/blauherd',camera:'https://zbag.roundshot.com/blauherd/'},
{id:'sunnegga',name:'Sunnegga',short:'Sunnegga',kind:'camera',lng:7.770068,lat:46.017246,alt:2288,story:'Its name means “Sunny Corner.” The funicular-served terrace is a gateway to the mountain: Leisee and summer paths on one side of the calendar, ski runs and the Wolli Beginners Park on the other.',source:'https://www.matterhornparadise.ch/en/experience/peaks/sunnegga',camera:'https://zbag.roundshot.com/sunnegga/'},
{id:'findeln',name:'Before the ski lifts',short:'Findeln',kind:'culture',lng:7.7689,lat:46.0125,story:'Findeln was once a seasonal farming settlement. Families grazed livestock and grew grain on these slopes; rye and barley cultivation continued until the end of the Second World War. Sun-darkened larch houses and barns preserve its Walser character.',source:'https://zermatt.swiss/en/p/hamlet-of-findeln-01tVj000005DfYoIAK'},
{id:'chapel',name:'A prayer for sunshine',short:'St James chapel',kind:'culture',lng:7.7686,lat:46.0123,story:'Findeln’s chapel is dedicated to St James the Elder and dates to 1691 or 1697. Farmers once made pilgrimages here for sunshine during wet hay harvests. The last such pilgrimage was recorded in 1954.',source:'https://zermatt.swiss/en/p/findeln-chapel-jakobus-der-aeltere-01tVj000005DqfZIAS'},
{id:'vrony',name:'Chez Vrony',short:'Chez Vrony',kind:'food',lng:7.7690,lat:46.0137,story:'A family house built in 1900 became a small tearoom in 1922. Winter service followed in 1953. The Julen family’s story connects Findeln’s farming past with the mountain hospitality visitors know today.',source:'https://zermatt.swiss/en/zermatt-tourism-meets/chez-vrony'},
{id:'findlerhof',name:'Findlerhof',short:'Findlerhof',kind:'food',lng:7.7684,lat:46.0120,story:'Tucked into Findeln near its white chapel, Findlerhof is reached through the hamlet’s narrow alley. The restaurant describes a winter approach from Sunnegga via piste six and a short walk. Check its own site for current access and opening details.',source:'https://www.findlerhof.ch/information'}];
